version: '2'

networks:
  default:
    name: local-stack

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
    - 9000:9000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
    external: true

