version: '2'

networks:
  default:
    external:
      name: network

services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    restart: always
    environment:
      - VIRTUAL_HOST=
      - VIRTUAL_PORT=80
#      - CERT_NAME=xn--80apqkhcno.xn--p1ai
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_EMAIL=
    ports:
      - '2224:22'
#      - '5050:5050'
    volumes:
      - './conf:/etc/gitlab'
      - './log:/var/log/gitlab'
      - './data:/var/opt/gitlab'
      - '/var/lib/docker/volumes/proxy_certs/_data/:/etc/gitlab/ssl/'
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - default

  gitlab-registry:
    container_name: gitlab-registry
    image: registry:latest
    restart: always
    volumes:
      - ./images:/var/lib/registry
    environment:
      - VIRTUAL_HOST=
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_EMAIL=
    networks:
      - default

  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:latest
        restart: always
    volumes:
      - ./srv/gitlab-runner/config:/etc/gitlab-runner
      - ./runner-user:/home/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default

#  pages:
#    container_name: gitlab-pages
#    image: genshen/gitlab-pages:latest
#    restart: always
#    environment:
#      - VIRTUAL_HOST=
#      - LETSENCRYPT_HOST=
#      - LETSENCRYPT_EMAIL=
#    networks:
#      - default
