version: "2"

networks:
  default:
    name: local-stack

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea-db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - ROOT_URL=http://host.docker.internal:3000
      - VIRTUAL_HOST=gitea.cubicmouse.asuscomm.com
      - LETSENCRYPT_HOST=gitea.cubicmouse.asuscomm.com
    restart: always
    volumes:
      - gitea_data:/data
    ports:
      - "3000:3000"
      - "222:22"

  gitea-db:
    image: postgres:latest
    container_name: gitea-db
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - gitea_postgres:/var/lib/postgresql/data

  drone-server:
    image: drone/drone:latest
    container_name: drone-server
    ports:
      - 8000:80
      - 4430:443
    volumes:
      - drone_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - DRONE_GITEA_SERVER=http://host.docker.internal:3000
      - DRONE_GITEA_CLIENT_ID=${DRONE_GITEA_CLIENT_ID}
      - DRONE_GITEA_CLIENT_SECRET=${DRONE_GITEA_CLIENT_SECRET}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_SERVER_HOST=host.docker.internal:8000
      - DRONE_SERVER_PROTO=http

  drone-runner:
    image: drone/drone-runner-docker:latest
    container_name: drone-runner
    ports:
      - "3002:3000"
    environment:
      - DRONE_RPC_HOST=host.docker.internal:8000
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME="drone-runner"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  gitea_data:
    external: true
  gitea_postgres:
    external: true
  drone_data:
    external: true
