version: '2'

networks:
  default:
    external:
      name: network

services:

  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2.0}
    container_name: mail-proxy
    restart: always
    environment:
      - VIRTUAL_HOST=
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_EMAIL=
    env_file: .env
#    logging:
#      driver: journald
#      options:
#        tag: mailu-front
    ports:
      - "110:110"
      - "143:143"
      - "993:993"
      - "995:995"
      - "25:25"
      - "465:465"
      - "587:587"
    expose:
    - '80'
    volumes:
      - "/var/lib/docker/volumes/proxy_certs/_data/{ domain }/:/certs"
      - ./overrides/nginx:/overrides:ro
    depends_on:
      - resolver
    dns:
      - 172.19.0.254
    networks:
      - default

  redis:
    image: redis:alpine
    restart: always
    container_name: mail-redis
    volumes:
      - "./redis:/data"
    depends_on:
      - resolver
    dns:
      - 172.19.0.254
    networks:
      - default

  imap:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2.0}
    restart: always
    container_name: mail-imap-dovecot
    env_file: .env
    volumes:
      - "./data:/data"
      - "./mail:/mail"
      - "./overrides/dovecot:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 172.19.0.254
    networks:
      - default

  smtp:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2.0}
    restart: always
    container_name: mail-smtp-postfix
    env_file: .env
#    logging:
#      driver: journald
#      options:
#        tag: mailu-smtp
    volumes:
      - "./data:/data"
      - "./overrides/postfix:/overrides:ro"
      - "./mailqueue:/queue"
    depends_on:
      - front
      - resolver
    dns:
      - 172.19.0.254
      networks:
      - default

  oletools:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}oletools:${MAILU_VERSION:-2.0}
    container_name: mail-oletools
#    hostname: oletools
    restart: always
    depends_on:
      - resolver
    dns:
      - 172.19.0.254
    networks:
      - default

  antispam:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2.0}
    restart: always
    container_name: mail-antispam-rspamd
#    hostname: antispam
    env_file: .env
#    logging:
#      driver: journald
#      options:
#        tag: mailu-antispam
    volumes:
      - "./filter:/var/lib/rspamd"
      - "./dkim:/dkim:ro"
      - "./overrides/rspamd:/etc/rspamd/override.d:ro"
    depends_on:
      - front
      - redis
      - oletools
      - antivirus
      - resolver
    dns:
      - 172.19.0.254
    networks:
      - default

  antivirus:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-2.0}
    restart: always
    container_name: mail-antivirus
    env_file: .env
    volumes:
    - "./filter:/data"
    depends_on:
      - resolver
    dns:
      - 172.19.0.254
    networks:
      - default

  webdav:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}radicale:${MAILU_VERSION:-2.0}
    restart: always
    container_name: mail-webdav
    env_file: .env
    volumes:
      - "./dav:/data"
    dns:
      - 172.19.0.254
    networks:
      - default

  admin:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2.0}
    restart: always
    container_name: mail-admin
    env_file: .env
#    logging:
#      driver: journald
#      options:
#        tag: mailu-admin
    volumes:
      - "./data:/data"
      - "./dkim:/dkim"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - redis
      - resolver
    dns:
      - 172.19.0.254
    networks:
      - default

  webmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-2.0}
    restart: always
    container_name: mail-web-roundcube
    env_file: .env
    volumes:
      - "./webmail:/data"
      - "./overrides/roundcube:/overrides:ro"
    depends_on:
      - front
    dns:
      - 172.19.0.254
    networks:
      - default

  fetchmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-2.0}
    restart: always
    container_name: mail-fetchmail
    env_file: .env
    volumes:
      - "./data:/data"
    depends_on:
      - resolver
      - admin
      - smtp
      - imap
    dns:
      - 172.19.0.254
    networks:
      - default

  resolver:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-2.0}
    restart: always
    container_name: mail-resolver-unbound
    env_file: .env
    networks:
      default:
        ipv4_address: 172.19.0.254
