version: '2'

networks:
  default:
    external:
      name: network

services:
  mail-autoconfig:
    container_name: mail-autoconfig
    image: nginx:latest
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - VIRTUAL_HOST=autoconfig., autodiscover.
      - LETSENCRYPT_HOST=autoconfig., autodiscover.
      - LETSENCRYPT_EMAIL=
    networks:
      - default
    links:
      - php-mail-autoconfig

  php-mail-autoconfig:
    container_name: php-mail-autoconfig
    image: php:7-fpm
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - default
