version: '2'

networks:
  default:
    external:
      name: network

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    restart: always
    environment:
      - VIRTUAL_HOST=
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_EMAIL=


    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
    external: true
