version: '2'

networks:
  default:
    name: local-stack

services:
  starter:
    container_name: starter
    image: httpd:alpine
    restart: always
    volumes:
      - starter_html:/usr/local/apache2/htdocs
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      
volumes:
  starter_html:
    external: true
